"""create tournaments tables

Revision ID: 2524cf13fb90
Revises: 343e0faee805
Create Date: 2026-04-03 07:06:28.066307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2524cf13fb90'
down_revision: Union[str, Sequence[str], None] = '343e0faee805'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournaments',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'REGISTRATION_OPEN', 'REGISTRATION_CLOSED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='tournament_status'), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('max_teams', sa.Integer(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_tournaments_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tournaments'))
    )
    op.create_index(op.f('ix_tournaments_name'), 'tournaments', ['name'], unique=True)
    op.create_index(op.f('ix_tournaments_owner_id'), 'tournaments', ['owner_id'], unique=False)
    op.create_table('tournament_participants',
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_tournament_participants_team_id_teams'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], name=op.f('fk_tournament_participants_tournament_id_tournaments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tournament_participants')),
    sa.UniqueConstraint('tournament_id', 'team_id', name='uq_tournament_participants_tournament_id_team_id')
    )
    op.create_index(op.f('ix_tournament_participants_team_id'), 'tournament_participants', ['team_id'], unique=False)
    op.create_index(op.f('ix_tournament_participants_tournament_id'), 'tournament_participants', ['tournament_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tournament_participants_tournament_id'), table_name='tournament_participants')
    op.drop_index(op.f('ix_tournament_participants_team_id'), table_name='tournament_participants')
    op.drop_table('tournament_participants')
    op.drop_index(op.f('ix_tournaments_owner_id'), table_name='tournaments')
    op.drop_index(op.f('ix_tournaments_name'), table_name='tournaments')
    op.drop_table('tournaments')
    # ### end Alembic commands ###
